export const actionTypes = {
  SET_VIDEOS: "SET_VIDEOS",
  SET_WATCH_LATER: "SET_WATCH_LATER",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_PLAYLIST_INFO: "SET_PLAYLIST_INFO",
  UPDATE_PLAYLIST_DETAILS: "UPDATE_PLAYLIST_DETAILS",
  REMOVE_PLAYLIST_INFO: "REMOVE_PLAYLIST_INFO",
};
